"Language" = "en"

[Tags]
"names.title.0" = [
    "Captain",
    "Privateer",
    "Commander",
    "Chief",
    "Marshal",
    "Colonel",
    "Dr.",
    "Doc",
    "Roughneck",
    "Specialist",
    "Overseer",
    "Warden",
    "Major",
    "Breaker",
    "Spacer",
    "Lander",
    "Tech",
    "Grounder",
]
"names.first.0" = [
    "John",
    "Jack",
    "Frank",
    "Gary",
    "Dom",
    "Mason",
    "Edward",
    "Arthur",
    "Robert",
    "Elias",
    "Pax",
    "Koyo",
    "Julian",
    "Lysander",
    "Hilly",
    "Valerius",
    "Darrow",
    "Gene",
    "Titus",
    "Cassius",
    "Buzz",
    "Ender",
    "Hadrian",
    "Fitcher",
    "Nero",
    "Walker",
    "Sterling",
    "Silas",
    "Cassia",
    "Amos",
    "Leto",
    "Miller",
    "Duncan",
    "Eli",
]
"names.last.0" = [
    "Ripley",
    "Bishop",
    "Hicks",
    "Jones",
    "Shaw",
    "Burke",
    "Jude",
    "Faris",
    "Rico",
    "O'Malley",
    "Bellona",
    "Fenris",
    "Shepard",
    "Belinsky",
    "Murtry",
    "Kovich",
    "Aldrin",
    "Holden",
    "Burton",
    "Wiggin",
    "Graff",
    "Kane",
    "Cooper",
]
"names.subtitle.0" = [
    "Sr.",
    "Jr.",
    "II",
    "III",
]
"names.nickname.0" = [
    "\"Cypher\"",
    "\"Nova\"",
    "\"Vector\"",
    "\"Jonnie\"",
    "\"Ghost\"",
    "\"Rook\"",
    "\"Knuckles\"",
    "\"Flash\"",
    "\"Old Man\"",
    "\"Beacon\"",
    "\"Check\"",
    "\"Brake\"",
]
"names.nickname.4" = [
    "\"Rusty\"",
    "\"Bucket\"",
    "\"Sparky\"",
    "\"Gasket\"",
    "\"Smokestack\"",
]