[Window]
TITLE = "Swordfish Engine"
FULLSCREEN = false
WIDTH = 1024
HEIGHT = 768
FRAMELIMIT = 120
UPDATELIMIT = 0
VSYNC = "Off"

[Profiler]
HISTORY = 300

[Renderer]
CLIP_NEAR = 0.10000000149011612
CLIP_FAR = 1000

