[[Bricks]]
ID      = "display_console"
Shape   = "block"
Tags    = [
    "metal",
    "buildable",
    "orientable",
    "convertable_truss",
]
[Bricks.Textures]
Default = ["display_console"]
Top     = ["panel.0"]
Bottom  = ["panel.0"]
Back    = ["vent"]
Left    = ["greeble1"]
Right   = ["greeble1"]
