[[Bricks]]
ID      = "display_control"
Shape   = "block"
Tags    = [
    "metal",
    "buildable",
    "convertable_truss",
]
[Bricks.Textures]
Default = "display_control"
Top     = "metal_panel"
Bottom  = "metal_panel"
Back    = "vent"
Left    = "greeble1"
Right   = "greeble1"
