[[Bricks]]
ID      = "display_monitor"
Shape   = "block"
Tags    = [
    "metal",
    "buildable",
    "convertable_truss",
]
[Bricks.Textures]
Default = ["display_monitor"]
Top     = ["metal_panel"]
Bottom  = ["metal_panel"]
Back    = ["vent"]
Left    = ["greeble1"]
Right   = ["greeble1"]
