[[Bricks]]
ID          = "glass"
Shape       = "any"
Transparent = true
Tags        = [
    "metal",
    "buildable",
    "convertable_truss",
]
[Bricks.Textures]
Connected = true
Default = ["glass.0"]
