[[Bricks]]
ID      = "storage"
Shape   = "block"
[Bricks.Textures]
Default = "storage_front"
Top     = "storage_top"
Bottom  = "storage_bottom"
Front   = "storage_front"
Back    = "storage_back"
Left    = "storage_side"
Right   = "storage_side"
