[Window]
TITLE = "Swordfish Engine"
FULLSCREEN = false
WIDTH = 1024
HEIGHT = 768
FRAMELIMIT = 120
UPDATELIMIT = 0
VSYNC = "Off"

[Profiler]
HISTORY = 300

[Renderer]
CLIP_NEAR = 0.1
CLIP_FAR = 1000

[Physics]
FIXED_TIMESTEP = 0.016

