[[Bodies]]
ID = "wb:f_alien"

[Bodies.States.standing]
front = ["characters/f_alien_standing.png"]

[Bodies.States.floating]
front = ["characters/f_alien_floating.png"]
back  = ["characters/f_alien_floating_back.png"]