[[Bodies]]
ID = "wb:m_alien"

[Bodies.States.standing]
front = ["characters/m_alien_standing.png"]

[Bodies.States.floating]
front = ["characters/m_alien_floating.png"]
back  = ["characters/m_alien_floating_back.png"]