ID = "waywardbeyond.server.core"
Name = "Wayward Beyond"
Description = "The space sandbox RPG server."
Author = "Chase Huegel"
Website = "https://github.com/ChaseHuegel"
Source = "https://github.com/ChaseHuegel/swordfish-engine"
Assemblies = [
    "WaywardBeyond.Server.Core.dll",
]