[[Bodies]]
ID = "wb:m_human"

[Bodies.States.standing]
front = ["characters/m_human_standing.png"]

[Bodies.States.floating]
front = ["characters/m_human_floating.png"]
back  = ["characters/m_human_floating_back.png"]