AllowScriptCompilation = false
LoadOrder = [
    "swordfish",
    "waywardbeyond.bricks",
    "waywardbeyond.skills",
    "waywardbeyond.bodies",
    "waywardbeyond.client",
    "waywardbeyond.server",
]