using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Swordfish.ECS.Generator;

/// <summary>
///     Generates the permutation-heavy component APIs (Alloc/AddOrUpdate/Remove/Query/QueryRef/QueryDirty/QueryRefDirty/QueryRemoved)
///     for arity 1..MaxComponents so the hot loops and overloads have a single source of truth.
///     Query loops iterate only the used slot range (high-water), skip bounds checks via ref-arithmetic,
///     skip exists checks in dense chunks, and offer delegate or struct-action callbacks.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class EcsComponentApiGenerator : IIncrementalGenerator
{
    public const int MaxComponents = 4;

    private const string Header =
        """
        // <auto-generated>
        // Generated by Swordfish.ECS.Generator. Do not edit.
        #nullable enable
        using System;
        using System.Collections.Generic;
        using System.Runtime.CompilerServices;
        using System.Runtime.InteropServices;
        using System.Threading.Tasks;

        namespace Swordfish.ECS;

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("Swordfish.ECS.Delegates.g.cs", SourceText.From(BuildDelegates(), Encoding.UTF8));
            ctx.AddSource("Swordfish.ECS.Actions.g.cs", SourceText.From(BuildActions(), Encoding.UTF8));
            ctx.AddSource("Swordfish.ECS.DataStore.g.cs", SourceText.From(BuildDataStore(), Encoding.UTF8));
            ctx.AddSource("Swordfish.ECS.Entity.g.cs", SourceText.From(BuildEntity(), Encoding.UTF8));
            ctx.AddSource("Swordfish.ECS.EntitySystem.g.cs", SourceText.From(BuildEntitySystem(), Encoding.UTF8));
        });
    }

    //  ------------------------------------------------------------------ single-line string helpers

    private static string T(int i) => $"T{i}";
    private static string TypeParams(int n) => string.Join(", ", Enumerable.Range(1, n).Select(T));
    private static string AngleTypeParams(int n) => $"<{TypeParams(n)}>";
    private static string CompParams(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"T{i} component{i}"));
    private static string CompArgs(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"component{i}"));
    private static string RefCompParams(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"in T{i} component{i}"));
    private static string RefRefCompParams(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"ref Ref<T{i}> component{i}"));
    private static string RefArgs(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"ref component{i}"));
    private static string OutDecls(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"out T{i} component{i}"));
    private static string OutArgs(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"out component{i}"));
    private static string DefaultArgs(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"default(T{i})"));
    private static string Discards(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"out T{i} _"));

    private static string MinChunkCount(int n) => n == 1 ? "chunks1.Length" : FoldMin(Enumerable.Range(1, n).Select(i => $"chunks{i}.Length").ToArray());
    private static string HighWater(int n) => n == 1 ? "chunk1.HighWater" : FoldMin(Enumerable.Range(1, n).Select(i => $"chunk{i}.HighWater").ToArray());
    private static string DenseCond(int n) => n == 1 ? "chunk1.Count == length" : string.Join(" && ", Enumerable.Range(1, n).Select(i => $"chunk{i}.Count == length"));
    private static string FoldMin(string[] xs) => xs.Length == 2 ? $"Math.Min({xs[0]}, {xs[1]})" : $"Math.Min({xs[0]}, {FoldMin(xs.Skip(1).ToArray())})";

    private static string ExistsCond(int n, bool inline, bool swapped)
    {
        if (n == 1)
        {
            return $"({FlagRef(1, inline)} & DataFlags.EXISTS) == 0";
        }

        var parts = new List<string>();
        if (swapped)
        {
            parts.Add("(Unsafe.Add(ref narrowFlagsRef, componentIndex) & DataFlags.EXISTS) == 0");
            parts.Add("(Unsafe.Add(ref wideFlagsRef, componentIndex) & DataFlags.EXISTS) == 0");
        }
        else
        {
            parts.Add($"({FlagRef(1, inline)} & DataFlags.EXISTS) == 0");
            parts.Add($"({FlagRef(2, inline)} & DataFlags.EXISTS) == 0");
        }

        for (var i = 3; i <= n; i++)
        {
            parts.Add($"({FlagRef(i, inline)} & DataFlags.EXISTS) == 0");
        }

        return string.Join(" || ", parts);
    }

    private static string DirtyCond(int n, bool inline) => string.Join(" && ", Enumerable.Range(1, n).Select(i => $"({FlagRef(i, inline)} & DataFlags.DIRTY) == 0"));
    private static string RemovedCond(int n, bool inline) => string.Join(" || ", Enumerable.Range(1, n).Select(i => $"({FlagRef(i, inline)} & (DataFlags.EXISTS | DataFlags.DIRTY)) != DataFlags.DIRTY"));

    //  Per-slot flag / component access. inline = derive refs from arrays inside a closure
    //  (Parallel.For cannot capture ref locals); otherwise use the pre-declared refs.
    private static string FlagRef(int i, bool inline) => inline
        ? $"Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(flags{i}), componentIndex)"
        : $"Unsafe.Add(ref flags{i}Ref, componentIndex)";
    private static string CompRef(int i, bool inline) => inline
        ? $"Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(components{i}), componentIndex)"
        : $"Unsafe.Add(ref components{i}Ref, componentIndex)";

    private static string CompRefArgs(int n, bool inline) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"in {CompRef(i, inline)}"));
    private static string RefAtGetArgs(int n) => string.Join(", ", Enumerable.Range(1, n).Select(i => $"in typed{i}.GetAtRef(chunkIndex, localEntity)"));

    //  ------------------------------------------------------------------ code writer

    /// <summary>
    ///     Thin wrapper over <see cref="IndentedTextWriter"/> that emits one statement per line at the current
    ///     indentation. Blocks are opened/closed via <see cref="EnterBlock"/>/<see cref="ExitBlock"/> so nesting
    ///     depth can never drift from call-site literals.
    /// </summary>
    private sealed class CodeWriter
    {
        private readonly IndentedTextWriter _writer;

        public CodeWriter()
        {
            _writer = new IndentedTextWriter(new StringWriter(), "    ");
        }

        public void Raw(string text) => _writer.Write(text);
        public void Line(string text = "")
        {
            _writer.Write(text);
            _writer.WriteLine();
        }

        /// <summary>Emits a truly blank line with no leading indentation.</summary>
        public void BlankLine() => _writer.WriteLineNoTabs(string.Empty);

        public void PushIndent() => _writer.Indent++;
        public void PopIndent() => _writer.Indent--;

        /// <summary>Writes the opening brace of a block and indents the following lines.</summary>
        public void EnterBlock()
        {
            Line("{");
            _writer.Indent++;
        }

        /// <summary>Dedents and writes the closing brace of a block.</summary>
        public void ExitBlock()
        {
            _writer.Indent--;
            Line("}");
        }

        public override string ToString() => _writer.InnerWriter.ToString();
    }

    //  ------------------------------------------------------------------ shared emitters

    private static void EmitMethod(CodeWriter writer, string name, string typeParams, string tail, int n, string? extraConstraint, string returnType = "void")
    {
        string returnPrefix = returnType == "void" ? "void " : $"{returnType} ";
        writer.Line($"public {returnPrefix}{name}<{typeParams}>({tail})");
        EmitConstraints(writer, n, extraConstraint);
        writer.EnterBlock();
    }

    private static void EmitConstraints(CodeWriter writer, int n, string? extra = null)
    {
        writer.PushIndent();
        for (var i = 1; i <= n; i++)
        {
            writer.Line($"where T{i} : struct, IDataComponent");
        }

        if (extra != null)
        {
            writer.Line(extra);
        }

        writer.PopIndent();
    }

    /// <summary>Emits `where` constraints terminating the declaration with a trailing semicolon.</summary>
    private static void EmitDeclConstraints(CodeWriter writer, int n)
    {
        writer.PushIndent();
        for (var i = 1; i <= n; i++)
        {
            bool last = i == n;
            writer.Line($"where T{i} : struct, IDataComponent{(last ? ";" : "")}");
        }

        writer.PopIndent();
    }

    /// <summary>Emits `if (parts[0][|| parts[1]...]) { action }`; continuations go on their own line at +1 indent.</summary>
    private static void EmitConditionBlock(CodeWriter writer, string[] conditions, string action)
    {
        if (conditions.Length == 1)
        {
            writer.Line($"if ({conditions[0]})");
        }
        else
        {
            writer.Line($"if ({conditions[0]}");
            writer.PushIndent();
            foreach (string continuation in conditions.Skip(1))
            {
                writer.Line($"|| {continuation}");
            }

            writer.PopIndent();
            writer.Line(")");
        }

        writer.EnterBlock();
        writer.Line(action);
        writer.ExitBlock();
    }

    private static void EmitStoreLookupBlock(CodeWriter writer, int n, string ret)
    {
        string[] conditions = Enumerable.Range(1, n).Select(i => $"!_stores.TryGetValue(typeof(T{i}), out ChunkedStore? store{i})").ToArray();
        EmitConditionBlock(writer, conditions, ret);
    }

    private static void EmitExistsAtBlock(CodeWriter writer, int n, string ret)
    {
        string[] conditions = Enumerable.Range(1, n).Select(i => $"!typed{i}.TryGetAt(chunkIndex, localEntity, out _)").ToArray();
        EmitConditionBlock(writer, conditions, ret);
    }

    private static void EmitTryGetAtBlock(CodeWriter writer, int n, string ret)
    {
        string[] conditions = Enumerable.Range(1, n).Select(i => $"!((ChunkedStore<T{i}>)store{i}).TryGetAt(chunkIndex, localEntity, out component{i})").ToArray();
        EmitConditionBlock(writer, conditions, ret);
    }

    private static void EmitSpanDecls(CodeWriter writer, int n)
    {
        foreach (int i in Enumerable.Range(1, n))
        {
            writer.Line($"Span<Chunk<T{i}>?> chunks{i};");
        }
    }

    private static void EmitSpanAssigns(CodeWriter writer, int n)
    {
        foreach (int i in Enumerable.Range(1, n))
        {
            writer.Line($"chunks{i} = CollectionsMarshal.AsSpan(((ChunkedStore<T{i}>)store{i}).Chunks);");
        }
    }

    private static void EmitExtract(CodeWriter writer, int n)
    {
        foreach (int i in Enumerable.Range(1, n))
        {
            writer.Line($"Chunk<T{i}>? chunk{i} = chunks{i}[chunkIndex];");
        }
    }

    private static void EmitLocals(CodeWriter writer, int n)
    {
        foreach (int i in Enumerable.Range(1, n))
        {
            writer.Line($"T{i}[] components{i} = chunk{i}.Components;");
            writer.Line($"byte[] flags{i} = chunk{i}.Flags;");
            writer.Line($"ref T{i} components{i}Ref = ref MemoryMarshal.GetArrayDataReference(components{i});");
            writer.Line($"ref byte flags{i}Ref = ref MemoryMarshal.GetArrayDataReference(flags{i});");
        }
    }

    private static void EmitNullCheck(CodeWriter writer, int n)
    {
        string[] conditions = Enumerable.Range(1, n).Select(i => $"chunk{i} is null").ToArray();
        EmitConditionBlock(writer, conditions, "continue;");
    }

    private static void EmitEmptyCheck(CodeWriter writer, int n)
    {
        string[] conditions = Enumerable.Range(1, n).Select(i => $"chunk{i}.Count == 0").ToArray();
        EmitConditionBlock(writer, conditions, "continue;");
    }

    /// <summary>NarrowSwap: point narrowFlagsRef at the store with fewer live entities so the exists test short-circuits.</summary>
    private static void EmitNarrowSwap(CodeWriter writer)
    {
        writer.Line("ref byte narrowFlagsRef = ref flags1Ref;");
        writer.Line("ref byte wideFlagsRef = ref flags2Ref;");
        writer.BlankLine();
        writer.Line("if (chunk2.Count < chunk1.Count)");
        writer.EnterBlock();
        writer.Line("narrowFlagsRef = ref flags2Ref;");
        writer.Line("wideFlagsRef = ref flags1Ref;");
        writer.ExitBlock();
    }

    //  ------------------------------------------------------------------ loop emitters

    /// <summary>The exists guard (optionally followed by the dirty guard) for the per-slot iteration.</summary>
    private static Action<CodeWriter> ExistsAndDirty(int n, bool swapped, bool inline, bool dirty, string action) => writer =>
    {
        EmitConditionBlock(writer, new[] { $"!dense && ({ExistsCond(n, inline, swapped)})" }, action);
        if (dirty)
        {
            EmitConditionBlock(writer, new[] { DirtyCond(n, inline) }, action);
        }
    };

    private static void EmitReadInvoke(CodeWriter writer, int n, bool inline)
    {
        writer.Line("int entity = componentIndex + offset;");
        writer.Line($"forEach(delta, this, entity, {CompRefArgs(n, inline)});");
    }

    private static void EmitRefInvoke(CodeWriter writer, int n, string caller)
    {
        for (int i = 1; i <= n; i++)
        {
            writer.Line($"Ref<T{i}> component{i} = new(ref {CompRef(i, inline: false)}, ref {FlagRef(i, inline: false)});");
        }

        writer.BlankLine();
        writer.Line("int entity = componentIndex + offset;");
        writer.Line($"{caller}(delta, this, entity, {RefArgs(n)});");
    }

    private static void EmitReadInvokeAs(CodeWriter writer, int n, string caller)
    {
        writer.Line("int entity = componentIndex + offset;");
        writer.Line($"{caller}(delta, this, entity, {CompRefArgs(n, inline: false)});");
    }

    private static void EmitSerialLoop(CodeWriter writer, Action<CodeWriter> emitFilter, Action<CodeWriter> emitInvoke)
    {
        writer.Line("for (var componentIndex = 0; componentIndex < length; componentIndex++)");
        writer.EnterBlock();
        emitFilter(writer);
        writer.BlankLine();
        emitInvoke(writer);
        writer.ExitBlock();
    }

    private static void EmitParallelLoop(CodeWriter writer, Action<CodeWriter> emitReturnFilter, Action<CodeWriter> emitContinueFilter, Action<CodeWriter> emitSerialInvoke, Action<CodeWriter> emitParallelInvoke)
    {
        writer.Line("if (length > 30_000)");
        writer.EnterBlock();
        writer.Line("Parallel.For(0, length, ForEachLocalEntity);");
        writer.BlankLine();
        writer.Line("void ForEachLocalEntity(int componentIndex, ParallelLoopState state)");
        writer.EnterBlock();
        emitReturnFilter(writer);
        writer.BlankLine();
        emitParallelInvoke(writer);
        writer.ExitBlock();
        writer.ExitBlock();
        writer.Line("else");
        writer.EnterBlock();
        writer.Line("for (var componentIndex = 0; componentIndex < length; componentIndex++)");
        writer.EnterBlock();
        emitContinueFilter(writer);
        writer.BlankLine();
        emitSerialInvoke(writer);
        writer.ExitBlock();
        writer.ExitBlock();
    }

    /// <summary>Emits the shared lock/span/minChunks/chunk-loop scaffolding, leaving the inner iteration to <paramref name="emitInner"/>.</summary>
    private static void EmitLoopBody(CodeWriter writer, int n, bool emptyCheck, bool dense, bool swap, Action<CodeWriter> emitInner)
    {
        EmitSpanDecls(writer, n);
        writer.BlankLine();
        writer.Line("lock (_chunkAndStoreLock)");
        writer.EnterBlock();
        EmitStoreLookupBlock(writer, n, "return;");
        writer.BlankLine();
        EmitSpanAssigns(writer, n);
        writer.ExitBlock();
        writer.BlankLine();
        writer.Line($"int minChunks = {MinChunkCount(n)};");
        writer.BlankLine();
        writer.Line("for (var chunkIndex = 0; chunkIndex < minChunks; chunkIndex++)");
        writer.EnterBlock();
        EmitExtract(writer, n);
        writer.BlankLine();
        EmitNullCheck(writer, n);
        writer.BlankLine();
        if (emptyCheck)
        {
            EmitEmptyCheck(writer, n);
            writer.BlankLine();
        }

        EmitLocals(writer, n);
        writer.Line("int offset = _chunkSize * chunkIndex;");
        writer.Line($"int length = {HighWater(n)};");
        if (dense)
        {
            writer.Line($"bool dense = {DenseCond(n)};");
        }

        if (swap && n >= 2)
        {
            writer.BlankLine();
            EmitNarrowSwap(writer);
        }

        writer.BlankLine();
        emitInner(writer);
        writer.ExitBlock();
    }

    private static void EmitLoopMethod(CodeWriter writer, string name, string typeParams, string tail, int n, string? extraConstraint, bool emptyCheck, bool dense, bool swap, Action<CodeWriter> emitInner)
    {
        EmitMethod(writer, name, typeParams, tail, n, extraConstraint);
        EmitLoopBody(writer, n, emptyCheck, dense, swap, emitInner);
        writer.ExitBlock();
    }

    //  ------------------------------------------------------------------ Delegates.g.cs

    private static string BuildDelegates()
    {
        var writer = new CodeWriter();
        writer.Raw(Header);
        writer.BlankLine();
        writer.Line("public delegate void ForEach(float delta, DataStore store, int entity);");
        writer.BlankLine();

        for (var n = 1; n <= MaxComponents; n++)
        {
            writer.Line($"public delegate void ForEach{AngleTypeParams(n)}(float delta, DataStore store, int entity, {RefCompParams(n)})");
            EmitDeclConstraints(writer, n);
            writer.BlankLine();

            writer.Line($"public delegate void ForEachRef{AngleTypeParams(n)}(float delta, DataStore store, int entity, {RefRefCompParams(n)})");
            EmitDeclConstraints(writer, n);
            writer.BlankLine();
        }

        return writer.ToString();
    }

    //  ------------------------------------------------------------------ Actions.g.cs

    private static string BuildActions()
    {
        var writer = new CodeWriter();
        writer.Raw(Header);
        writer.BlankLine();

        //  The no-argument interface is hand-typed here since it has no type parameters.
        writer.Line("public interface IForEach");
        writer.EnterBlock();
        writer.Line("void Execute(float delta, DataStore store, int entity);");
        writer.ExitBlock();
        writer.BlankLine();

        for (var n = 1; n <= MaxComponents; n++)
        {
            writer.Line($"public interface IForEach{AngleTypeParams(n)}");
            EmitConstraints(writer, n);
            writer.EnterBlock();
            writer.Line($"void Execute(float delta, DataStore store, int entity, {RefCompParams(n)});");
            writer.ExitBlock();
            writer.BlankLine();

            writer.Line($"public interface IForEachRef{AngleTypeParams(n)}");
            EmitConstraints(writer, n);
            writer.EnterBlock();
            writer.Line($"void Execute(float delta, DataStore store, int entity, {RefRefCompParams(n)});");
            writer.ExitBlock();
            writer.BlankLine();
        }

        return writer.ToString();
    }

    //  ------------------------------------------------------------------ DataStore.g.cs

    private static void EmitNoComponentAction(CodeWriter writer)
    {
        EmitMethod(writer, "Query", "TAction", "float delta, ref TAction action", 0, "where TAction : struct, IForEach");
        writer.Line("lock (_chunkAndStoreLock)");
        writer.EnterBlock();
        writer.Line("lock (_recycleLock)");
        writer.EnterBlock();
        writer.Line("TAction local = action;");
        writer.BlankLine();
        writer.Line("for (var entity = 1; entity <= _lastEntity; entity++)");
        writer.EnterBlock();
        writer.Line("if (_recycledSet.Contains(entity))");
        writer.EnterBlock();
        writer.Line("continue;");
        writer.ExitBlock();
        writer.BlankLine();
        writer.Line("local.Execute(delta, this, entity);");
        writer.ExitBlock();
        writer.BlankLine();
        writer.Line("action = local;");
        writer.ExitBlock();
        writer.ExitBlock();
        writer.ExitBlock();
    }

    private static void EmitAlloc(CodeWriter writer, int n)
    {
        EmitMethod(writer, "Alloc", TypeParams(n), CompParams(n), n, null, "int");
        writer.Line("lock (_chunkAndStoreLock)");
        writer.EnterBlock();
        writer.Line("int entity = AllocNewEntity();");
        writer.Line("(int chunkIndex, int localEntity) = ToChunkSpace(entity);");
        writer.BlankLine();
        for (int i = 1; i <= n; i++)
        {
            writer.Line($"SetAt(chunkIndex, localEntity, component{i}, true);");
        }

        writer.BlankLine();
        writer.Line("return entity;");
        writer.ExitBlock();
        writer.ExitBlock();
    }

    private static void EmitAddOrUpdate(CodeWriter writer, int n)
    {
        EmitMethod(writer, "AddOrUpdate", TypeParams(n), $"int entity, {CompParams(n)}", n, null);
        writer.Line("lock (_chunkAndStoreLock)");
        writer.EnterBlock();
        writer.Line("(int chunkIndex, int localEntity) = ToChunkSpace(entity);");
        writer.BlankLine();
        for (int i = 1; i <= n; i++)
        {
            writer.Line($"SetAt(chunkIndex, localEntity, component{i}, true);");
        }

        writer.ExitBlock();
        writer.ExitBlock();
    }

    private static void EmitRemove(CodeWriter writer, int n)
    {
        EmitMethod(writer, "Remove", TypeParams(n), "int entity", n, null, "bool");
        writer.Line("lock (_chunkAndStoreLock)");
        writer.EnterBlock();
        EmitStoreLookupBlock(writer, n, "return false;");
        writer.BlankLine();
        writer.Line("(int chunkIndex, int localEntity) = ToChunkSpace(entity);");
        writer.BlankLine();
        for (int i = 1; i <= n; i++)
        {
            writer.Line($"store{i}.SetAt(chunkIndex, localEntity, false);");
        }

        writer.BlankLine();
        writer.Line("return true;");
        writer.ExitBlock();
        writer.ExitBlock();
    }

    private static void EmitQueryFamily(CodeWriter writer, int n, bool dirty, bool parallel)
    {
        string name = parallel
            ? (dirty ? "QueryDirtyParallel" : "QueryParallel")
            : (dirty ? "QueryDirty" : "Query");
        string tail = $"float delta, ForEach{AngleTypeParams(n)} forEach";

        if (!parallel)
        {
            EmitLoopMethod(
                writer, name, TypeParams(n), tail, n, null,
                emptyCheck: true, dense: true, swap: true,
                emitInner: w => EmitSerialLoop(w, ExistsAndDirty(n, swapped: true, inline: false, dirty, "continue;"), flow => EmitReadInvoke(flow, n, inline: false)));
            return;
        }

        EmitLoopMethod(
            writer, name, TypeParams(n), tail, n, null,
            emptyCheck: true, dense: true, swap: false,
            emitInner: w => EmitParallelLoop(
                w,
                ExistsAndDirty(n, swapped: false, inline: true, dirty, "return;"),
                ExistsAndDirty(n, swapped: false, inline: false, dirty, "continue;"),
                flow => EmitReadInvoke(flow, n, inline: false),
                flow => EmitReadInvoke(flow, n, inline: true)));
    }

    private static void EmitRefFamily(CodeWriter writer, int n, bool dirty)
    {
        string name = dirty ? "QueryRefDirty" : "QueryRef";
        string tail = $"float delta, ForEachRef{AngleTypeParams(n)} forEach";
        EmitLoopMethod(
            writer, name, TypeParams(n), tail, n, null,
            emptyCheck: true, dense: true, swap: true,
            emitInner: w => EmitSerialLoop(w, ExistsAndDirty(n, swapped: true, inline: false, dirty, "continue;"), flow => EmitRefInvoke(flow, n, "forEach")));
    }

    private static void EmitRemovedFamily(CodeWriter writer, int n)
    {
        string tail = $"float delta, ForEach{AngleTypeParams(n)} forEach";
        EmitLoopMethod(
            writer, "QueryRemoved", TypeParams(n), tail, n, null,
            emptyCheck: false, dense: false, swap: false,
            emitInner: w => EmitSerialLoop(w, flow => EmitConditionBlock(flow, new[] { RemovedCond(n, inline: false) }, "continue;"), flow => EmitReadInvoke(flow, n, inline: false)));
    }

    private static void EmitActionFamily(CodeWriter writer, int n, string kind)
    {
        bool write = kind == "QueryRef" || kind == "QueryRefDirty";
        bool dirty = kind == "QueryDirty" || kind == "QueryRefDirty";
        bool removed = kind == "QueryRemoved";
        string iface = write ? "IForEachRef" : "IForEach";
        string typeParams = $"{TypeParams(n)}, TAction";
        string extra = $"where TAction : struct, {iface}{AngleTypeParams(n)}";
        string tail = "float delta, ref TAction action";

        //  Copy the action to a local so the JIT can inline Execute against a register-resident
        //  struct; write back once so mutable accumulators survive.
        EmitMethod(writer, kind, typeParams, tail, n, extra);
        writer.Line("TAction local = action;");
        writer.BlankLine();

        Action<CodeWriter> filter = removed
            ? flow => EmitConditionBlock(flow, new[] { RemovedCond(n, inline: false) }, "continue;")
            : ExistsAndDirty(n, swapped: true, inline: false, dirty, "continue;");
        Action<CodeWriter> invoke = removed || !write
            ? flow => EmitReadInvokeAs(flow, n, "local.Execute")
            : flow => EmitRefInvoke(flow, n, "local.Execute");

        EmitLoopBody(writer, n, emptyCheck: !removed, dense: !removed, swap: !removed, emitInner: w => EmitSerialLoop(w, filter, invoke));
        writer.BlankLine();
        writer.Line("action = local;");
        writer.ExitBlock();
    }

    private static void EmitSingleEntityActionFamily(CodeWriter writer, int n, string kind)
    {
        bool write = kind == "QueryRef";
        string iface = write ? "IForEachRef" : "IForEach";
        string typeParams = $"{TypeParams(n)}, TAction";
        string extra = $"where TAction : struct, {iface}{AngleTypeParams(n)}";
        string tail = "int entity, float delta, ref TAction action";

        EmitMethod(writer, kind, typeParams, tail, n, extra);
        writer.Line("lock (_chunkAndStoreLock)");
        writer.EnterBlock();
        EmitStoreLookupBlock(writer, n, "return;");
        writer.BlankLine();
        for (int i = 1; i <= n; i++)
        {
            writer.Line($"ChunkedStore<T{i}> typed{i} = (ChunkedStore<T{i}>)store{i};");
        }

        writer.Line("(int chunkIndex, int localEntity) = ToChunkSpace(entity);");
        writer.BlankLine();
        EmitExistsAtBlock(writer, n, "return;");
        writer.BlankLine();
        if (write)
        {
            for (int i = 1; i <= n; i++)
            {
                writer.Line($"Ref<T{i}> component{i} = new(ref typed{i}.GetAtRef(chunkIndex, localEntity), ref typed{i}.Chunks[chunkIndex]!.Flags[localEntity]);");
            }
        }

        writer.Line("TAction local = action;");
        writer.BlankLine();
        if (write)
        {
            writer.Line($"local.Execute(delta, this, entity, {RefArgs(n)});");
        }
        else
        {
            writer.Line($"local.Execute(delta, this, entity, {RefAtGetArgs(n)});");
        }

        writer.ExitBlock();
        writer.ExitBlock();
    }

    private static void EmitSingleEntityQuery(CodeWriter writer, int n, bool refQuery)
    {
        string name = refQuery ? "QueryRef" : "Query";
        string forEachType = refQuery ? $"ForEachRef{AngleTypeParams(n)}" : $"ForEach{AngleTypeParams(n)}";
        string tail = $"int entity, float delta, {forEachType} forEach";

        EmitMethod(writer, name, TypeParams(n), tail, n, null);
        writer.Line("lock (_chunkAndStoreLock)");
        writer.EnterBlock();
        EmitStoreLookupBlock(writer, n, "return;");
        writer.BlankLine();
        for (int i = 1; i <= n; i++)
        {
            writer.Line($"ChunkedStore<T{i}> typed{i} = (ChunkedStore<T{i}>)store{i};");
        }

        writer.Line("(int chunkIndex, int localEntity) = ToChunkSpace(entity);");
        writer.BlankLine();
        EmitExistsAtBlock(writer, n, "return;");
        writer.BlankLine();
        if (refQuery)
        {
            for (int i = 1; i <= n; i++)
            {
                writer.Line($"Ref<T{i}> component{i} = new(ref typed{i}.GetAtRef(chunkIndex, localEntity), ref typed{i}.Chunks[chunkIndex]!.Flags[localEntity]);");
            }

            writer.BlankLine();
            writer.Line($"forEach(delta, this, entity, {RefArgs(n)});");
        }
        else
        {
            writer.Line($"forEach(delta, this, entity, {RefAtGetArgs(n)});");
        }

        writer.ExitBlock();
        writer.ExitBlock();
    }

    private static void EmitTryGet(CodeWriter writer, int n, bool byUuid)
    {
        string decls = OutDecls(n);
        string tail = byUuid ? $"Uuid uuid, {decls}" : $"int entity, {decls}";
        EmitMethod(writer, "TryGet", TypeParams(n), tail, n, null, "bool");
        writer.Line("lock (_chunkAndStoreLock)");
        writer.EnterBlock();
        for (int i = 1; i <= n; i++)
        {
            writer.Line($"component{i} = default!;");
        }

        if (byUuid)
        {
            writer.BlankLine();
            writer.Line("if (!_slotByUuid.TryGetValue(uuid, out int entity))");
            writer.EnterBlock();
            writer.Line("return false;");
            writer.ExitBlock();
        }

        writer.BlankLine();
        EmitStoreLookupBlock(writer, n, "return false;");
        writer.BlankLine();
        writer.Line("(int chunkIndex, int localEntity) = ToChunkSpace(entity);");
        writer.BlankLine();
        EmitTryGetAtBlock(writer, n, "return false;");
        writer.BlankLine();
        writer.Line("return true;");
        writer.ExitBlock();
        writer.ExitBlock();
    }

    private static string BuildDataStore()
    {
        var writer = new CodeWriter();
        writer.Raw(Header);
        writer.BlankLine();
        writer.Line("public partial class DataStore");
        writer.EnterBlock();
        EmitNoComponentAction(writer);
        writer.BlankLine();

        for (var n = 1; n <= MaxComponents; n++)
        {
            EmitSingleEntityActionFamily(writer, n, "Query");
            writer.BlankLine();
            EmitSingleEntityActionFamily(writer, n, "QueryRef");
            writer.BlankLine();
        }

        for (var n = 1; n <= MaxComponents; n++)
        {
            EmitAlloc(writer, n);
            writer.BlankLine();
            EmitAddOrUpdate(writer, n);
            writer.BlankLine();
            EmitRemove(writer, n);
            writer.BlankLine();

            EmitQueryFamily(writer, n, dirty: false, parallel: false);
            writer.BlankLine();
            EmitQueryFamily(writer, n, dirty: true, parallel: false);
            writer.BlankLine();
            EmitRefFamily(writer, n, dirty: false);
            writer.BlankLine();
            EmitRefFamily(writer, n, dirty: true);
            writer.BlankLine();
            EmitRemovedFamily(writer, n);
            writer.BlankLine();

            EmitQueryFamily(writer, n, dirty: false, parallel: true);
            writer.BlankLine();
            EmitQueryFamily(writer, n, dirty: true, parallel: true);
            writer.BlankLine();

            EmitActionFamily(writer, n, "Query");
            writer.BlankLine();
            EmitActionFamily(writer, n, "QueryDirty");
            writer.BlankLine();
            EmitActionFamily(writer, n, "QueryRef");
            writer.BlankLine();
            EmitActionFamily(writer, n, "QueryRefDirty");
            writer.BlankLine();
            EmitActionFamily(writer, n, "QueryRemoved");
            writer.BlankLine();

            EmitSingleEntityQuery(writer, n, refQuery: false);
            writer.BlankLine();
            EmitSingleEntityQuery(writer, n, refQuery: true);
            writer.BlankLine();
            EmitTryGet(writer, n, byUuid: false);
            writer.BlankLine();
            EmitTryGet(writer, n, byUuid: true);
            writer.BlankLine();
        }

        writer.ExitBlock();
        return writer.ToString();
    }

    //  ------------------------------------------------------------------ Entity.g.cs

    private static void EmitEntityMethods(CodeWriter writer, int n)
    {
        EmitMethod(writer, "Add", TypeParams(n), "", n, null, "bool");
        writer.Line($"if (Has{AngleTypeParams(n)}())");
        writer.EnterBlock();
        writer.Line("return false;");
        writer.ExitBlock();
        writer.BlankLine();
        writer.Line($"_dataStore.AddOrUpdate(Ptr, {DefaultArgs(n)});");
        writer.Line("return true;");
        writer.ExitBlock();

        EmitMethod(writer, "AddOrUpdate", TypeParams(n), CompParams(n), n, null);
        writer.Line($"_dataStore.AddOrUpdate(Ptr, {CompArgs(n)});");
        writer.ExitBlock();

        EmitMethod(writer, "Remove", TypeParams(n), "", n, null, "bool");
        writer.Line($"return _dataStore.Remove{AngleTypeParams(n)}(Ptr);");
        writer.ExitBlock();

        EmitMethod(writer, "Has", TypeParams(n), "", n, null, "bool");
        writer.Line($"return _dataStore.TryGet{AngleTypeParams(n)}(Ptr, {Discards(n)});");
        writer.ExitBlock();

        EmitMethod(writer, "TryGet", TypeParams(n), OutDecls(n), n, null, "bool");
        writer.Line($"return _dataStore.TryGet{AngleTypeParams(n)}(Ptr, {OutArgs(n)});");
        writer.ExitBlock();
    }

    private static string BuildEntity()
    {
        var writer = new CodeWriter();
        writer.Raw(Header);
        writer.BlankLine();
        writer.Line("public readonly partial struct Entity");
        writer.EnterBlock();
        for (var n = 1; n <= MaxComponents; n++)
        {
            EmitEntityMethods(writer, n);
            writer.BlankLine();
        }

        writer.ExitBlock();
        return writer.ToString();
    }

    //  ------------------------------------------------------------------ EntitySystem.g.cs

    private static string BuildEntitySystemClass(int n, bool refQuery)
    {
        var writer = new CodeWriter();
        string className = refQuery ? $"EntitySystemRef{AngleTypeParams(n)}" : $"EntitySystem{AngleTypeParams(n)}";
        string baseDelegate = refQuery ? $"ForEachRef{AngleTypeParams(n)}" : $"ForEach{AngleTypeParams(n)}";
        string queryName = refQuery ? "QueryRef" : "Query";
        string onTickParams = refQuery ? RefRefCompParams(n) : RefCompParams(n);
        string ctorName = refQuery ? "EntitySystemRef" : "EntitySystem";

        writer.Line($"public abstract class {className} : IEntitySystem");
        EmitConstraints(writer, n);
        writer.EnterBlock();
        writer.Line($"private readonly {baseDelegate} _onTick;");
        writer.BlankLine();
        writer.Line($"protected {ctorName}()");
        writer.EnterBlock();
        writer.Line("_onTick = OnTick;");
        writer.ExitBlock();
        writer.BlankLine();
        writer.Line("public void Tick(float delta, DataStore store)");
        writer.EnterBlock();
        writer.Line($"store.{queryName}{AngleTypeParams(n)}(delta, _onTick);");
        writer.ExitBlock();
        writer.BlankLine();
        writer.Line($"protected abstract void OnTick(float delta, DataStore store, int entity, {onTickParams});");
        writer.ExitBlock();
        return writer.ToString();
    }

    private static string BuildEntitySystem()
    {
        var writer = new CodeWriter();
        writer.Raw(Header);
        writer.BlankLine();
        for (var n = 1; n <= MaxComponents; n++)
        {
            writer.Raw(BuildEntitySystemClass(n, refQuery: false));
            writer.BlankLine();
            writer.Raw(BuildEntitySystemClass(n, refQuery: true));
            writer.BlankLine();
        }

        return writer.ToString();
    }
}