"Language" = "en"

[Translations]
"ui.text.none" = "<none>"

"ui.label.timePlayed" = "Time played"
"ui.label.lastPlayed" = "Last played"

"ui.word.hours" = "hours"
"ui.word.minutes" = "minutes"
"ui.word.seconds" = "seconds"

"ui.label.spacer.s" = "S"
"ui.label.spacer.p" = "P"
"ui.label.spacer.a" = "A"
"ui.label.spacer.c" = "C"
"ui.label.spacer.e" = "E"
"ui.label.spacer.r" = "R"

"ui.menu.feedback" = "Feedback"
"ui.button.feedback" = "Send feedback"
"ui.field.feedback.description" = "Enter details (max 500 characters)..."
"ui.field.feedback.contact" = "Contact (optional)"

"ui.menu.playtest" = "In-development Playtest"
"ui.text.playtest" = "This is an evolving version of Wayward Beyond in early development. Please wishlist it if you are interested in the release!\n\nFeatures and content will be added and changed throughout this playtest. I greatly appreciate feedback on any ideas, suggestions, or bugs, which can be submitted from the menu or by joining the Discord.\n\nThank you for trying out Wayward Beyond!\n-Seven"

"ui.button.submit" = "Submit"
"ui.button.back" = "Back"
"ui.button.close" = "Close"

"ui.button.selectSave" = "Continue"
"ui.button.newSave" = "Create save"
"ui.button.settings" = "Settings"
"ui.button.quit" = "Quit game"

"ui.button.continue" = "Continue"
"ui.button.saveAndExit" = "Save & exit"

"ui.menu.createSave" = "Create Save"
"ui.menu.saves" = "Game Saves"
"ui.button.newGame" = "Create"
"ui.field.saveName" = "Enter name..."
"ui.field.saveSeed" = "[Random seed]"

"ui.button.loadSave" = "Embark"

"ui.button.selectCharacter" = "Select character"
"ui.button.newCharacter" = "Create character"

"ui.menu.createCharacter" = "Create Character"
"ui.menu.characters" = "Characters"
"ui.button.createCharacter" = "Create"
"ui.field.characterName" = "Enter name..."

"ui.menu.display" = "Display"
"ui.setting.vsync" = "VSync"
"ui.setting.fullscreen" = "Fullscreen"
"ui.setting.borderless" = "Borderless"
"ui.setting.msaa" = "Anti-aliasing"

"ui.menu.gameplay" = "Gameplay"
"ui.setting.fov" = "Field of view"
"ui.setting.autosave" = "Autosave"
"ui.setting.autosave.interval.minutes" = "  Minutes"
"ui.setting.controlHints" = "Control hints"

"ui.menu.controls" = "Controls"
"ui.setting.mouseSensitivity" = "Sensitivity"

"ui.menu.volume" = "Volume"
"ui.setting.volume.master" = "Master"
"ui.setting.volume.interface" = "Interface"
"ui.setting.volume.effects" = "Effects"
"ui.setting.volume.music" = "Music"

"ui.field.spacer" = "S.P.A.C.E.R"
"ui.field.spacer.description" = "Your S.P.A.C.E.R rating is an official assessment of key attributes in becoming a space colonist."
"ui.field.spacer.points" = "Points remaining"
"ui.field.strength" = "Strength"
"ui.field.precision" = "Precision"
"ui.field.awareness" = "Awareness"
"ui.field.charisma" = "Charisma"
"ui.field.education" = "Education"
"ui.field.resolve" = "Resolve"

"ui.hint.changeShape" = "R: Change shape"
"ui.hint.changeOrientation" = "T: Change orientation"
"ui.hint.snapBrick" = "Shift: Snap brick"
"ui.hint.pickBrick" = "MMB: Pick brick"
"ui.hint.breakBrick" = "LMB: Break brick"
"ui.hint.placeBrick" = "RMB: Place brick"
"ui.hint.movement.roll" = "Q/E: Roll"
"ui.hint.movement.up" = "Space: Up"
"ui.hint.movement.down" = "Ctrl: Down"
"ui.hint.movement" = "W/A/S/D: Fly"
"ui.hint.quit" = "Esc: Pause"
"ui.hint.quicksave" = "F5: Quicksave"
"ui.hint.inventory" = "Tab: Inventory"
