"Language" = "en"

[Translations]
"formats.name.wb:m_human" = "{Title} {First} {Nickname} {Last} {Subtitle}"
"formats.name.wb:f_human" = "{Title} {First} {Nickname} {Last} {Subtitle}"
"formats.name.wb:m_alien" = "{Title} {First} {Nickname} {Last}{Subtitle}"
"formats.name.wb:f_alien" = "{Title} {First} {Nickname} {Last}{Subtitle}"
"formats.name.wb:bot" = "{Nickname} {Title}{First}-{Last} {Subtitle}"
"formats.name.save" = "{Nickname} {Title} {First} {Last} {Subtitle}"
