using Silk.NET.Input;

namespace Swordfish.Util;

public static class SilkInputExtensions
{
    public static Library.IO.CursorState ToCursorState(this CursorMode cursorMode)
    {
        return cursorMode switch
        {
            CursorMode.Normal => Library.IO.CursorState.NORMAL,
            CursorMode.Hidden => Library.IO.CursorState.HIDDEN,
            CursorMode.Disabled => Library.IO.CursorState.LOCKED,
            CursorMode.Raw => Library.IO.CursorState.LOCKED,
            _ => Library.IO.CursorState.NORMAL,
        };
    }

    public static Library.IO.MouseButton ToSwordfishMouseButton(this MouseButton silkMouseButton)
    {
        return silkMouseButton switch
        {
            MouseButton.Left => Library.IO.MouseButton.LEFT,
            MouseButton.Right => Library.IO.MouseButton.RIGHT,
            MouseButton.Middle => Library.IO.MouseButton.MIDDLE,
            _ => Library.IO.MouseButton.UNKNOWN,
        };
    }

    public static Library.IO.Key ToSwordfishKey(this Key key) => key switch
    {
        Key.Backspace => Library.IO.Key.BACKSPACE,
        Key.Tab => Library.IO.Key.TAB,
        Key.Enter => Library.IO.Key.ENTER,
        Key.Pause => Library.IO.Key.PAUSE,
        Key.CapsLock => Library.IO.Key.CAPSLOCK,
        Key.Escape => Library.IO.Key.ESC,
        Key.Space => Library.IO.Key.SPACE,
        Key.PageUp => Library.IO.Key.PAGE_UP,
        Key.PageDown => Library.IO.Key.PAGE_DOWN,
        Key.End => Library.IO.Key.END,
        Key.Home => Library.IO.Key.HOME,
        Key.Left => Library.IO.Key.LEFT_ARROW,
        Key.Up => Library.IO.Key.UP_ARROW,
        Key.Right => Library.IO.Key.RIGHT_ARROW,
        Key.Down => Library.IO.Key.DOWN_ARROW,
        Key.PrintScreen => Library.IO.Key.PRINT_SCREEN,
        Key.Insert => Library.IO.Key.INSERT,
        Key.Delete => Library.IO.Key.DELETE,
        Key.Number0 => Library.IO.Key.D0,
        Key.Number1 => Library.IO.Key.D1,
        Key.Number2 => Library.IO.Key.D2,
        Key.Number3 => Library.IO.Key.D3,
        Key.Number4 => Library.IO.Key.D4,
        Key.Number5 => Library.IO.Key.D5,
        Key.Number6 => Library.IO.Key.D6,
        Key.Number7 => Library.IO.Key.D7,
        Key.Number8 => Library.IO.Key.D8,
        Key.Number9 => Library.IO.Key.D9,
        Key.A => Library.IO.Key.A,
        Key.B => Library.IO.Key.B,
        Key.C => Library.IO.Key.C,
        Key.D => Library.IO.Key.D,
        Key.E => Library.IO.Key.E,
        Key.F => Library.IO.Key.F,
        Key.G => Library.IO.Key.G,
        Key.H => Library.IO.Key.H,
        Key.I => Library.IO.Key.I,
        Key.J => Library.IO.Key.J,
        Key.K => Library.IO.Key.K,
        Key.L => Library.IO.Key.L,
        Key.M => Library.IO.Key.M,
        Key.N => Library.IO.Key.N,
        Key.O => Library.IO.Key.O,
        Key.P => Library.IO.Key.P,
        Key.Q => Library.IO.Key.Q,
        Key.R => Library.IO.Key.R,
        Key.S => Library.IO.Key.S,
        Key.T => Library.IO.Key.T,
        Key.U => Library.IO.Key.U,
        Key.V => Library.IO.Key.V,
        Key.W => Library.IO.Key.W,
        Key.X => Library.IO.Key.X,
        Key.Y => Library.IO.Key.Y,
        Key.Z => Library.IO.Key.Z,
        Key.Keypad0 => Library.IO.Key.NUMPAD_0,
        Key.Keypad1 => Library.IO.Key.NUMPAD_1,
        Key.Keypad2 => Library.IO.Key.NUMPAD_2,
        Key.Keypad3 => Library.IO.Key.NUMPAD_3,
        Key.Keypad4 => Library.IO.Key.NUMPAD_4,
        Key.Keypad5 => Library.IO.Key.NUMPAD_5,
        Key.Keypad6 => Library.IO.Key.NUMPAD_6,
        Key.Keypad7 => Library.IO.Key.NUMPAD_7,
        Key.Keypad8 => Library.IO.Key.NUMPAD_8,
        Key.Keypad9 => Library.IO.Key.NUMPAD_9,
        Key.KeypadMultiply => Library.IO.Key.MULTIPLY,
        Key.KeypadAdd => Library.IO.Key.ADD,
        Key.KeypadSubtract => Library.IO.Key.SUBTRACT,
        Key.KeypadDecimal => Library.IO.Key.DECIMAL,
        Key.KeypadDivide => Library.IO.Key.DIVIDE,
        Key.F1 => Library.IO.Key.F1,
        Key.F2 => Library.IO.Key.F2,
        Key.F3 => Library.IO.Key.F3,
        Key.F4 => Library.IO.Key.F4,
        Key.F5 => Library.IO.Key.F5,
        Key.F6 => Library.IO.Key.F6,
        Key.F7 => Library.IO.Key.F7,
        Key.F8 => Library.IO.Key.F8,
        Key.F9 => Library.IO.Key.F9,
        Key.F10 => Library.IO.Key.F10,
        Key.F11 => Library.IO.Key.F11,
        Key.F12 => Library.IO.Key.F12,
        Key.F13 => Library.IO.Key.F13,
        Key.F14 => Library.IO.Key.F14,
        Key.F15 => Library.IO.Key.F15,
        Key.F16 => Library.IO.Key.F16,
        Key.F17 => Library.IO.Key.F17,
        Key.F18 => Library.IO.Key.F18,
        Key.F19 => Library.IO.Key.F19,
        Key.F20 => Library.IO.Key.F20,
        Key.F21 => Library.IO.Key.F21,
        Key.F22 => Library.IO.Key.F22,
        Key.F23 => Library.IO.Key.F23,
        Key.F24 => Library.IO.Key.F24,
        Key.NumLock => Library.IO.Key.NUMLOCK,
        Key.ScrollLock => Library.IO.Key.SCROLL_LOCK,
        Key.ShiftLeft => Library.IO.Key.LEFT_SHIFT,
        Key.ShiftRight => Library.IO.Key.RIGHT_SHIFT,
        Key.ControlLeft => Library.IO.Key.LEFT_CONTROL,
        Key.ControlRight => Library.IO.Key.RIGHT_CONTROL,
        Key.AltLeft => Library.IO.Key.LEFT_ALT,
        Key.AltRight => Library.IO.Key.RIGHT_ALT,
        _ => Library.IO.Key.NONE
    };
}