using Silk.NET.Input;

namespace Swordfish.Input;

public static class SilkInputExtensions
{
    public static Library.IO.CursorOptions ToCursorState(this CursorMode cursorMode)
    {
        return cursorMode switch
        {
            CursorMode.Normal => Library.IO.CursorOptions.None,
            CursorMode.Hidden => Library.IO.CursorOptions.Hidden,
            CursorMode.Disabled => Library.IO.CursorOptions.Locked | Library.IO.CursorOptions.Hidden,
            CursorMode.Raw => Library.IO.CursorOptions.Locked | Library.IO.CursorOptions.Hidden,
            _ => Library.IO.CursorOptions.None,
        };
    }

    public static Library.IO.MouseButton ToSwordfishMouseButton(this MouseButton silkMouseButton)
    {
        return silkMouseButton switch
        {
            MouseButton.Left => Library.IO.MouseButton.Left,
            MouseButton.Right => Library.IO.MouseButton.Right,
            MouseButton.Middle => Library.IO.MouseButton.Middle,
            _ => Library.IO.MouseButton.Unknown,
        };
    }

    public static Library.IO.Key ToSwordfishKey(this Key key) => key switch
    {
        Key.Backspace => Library.IO.Key.Backspace,
        Key.Tab => Library.IO.Key.Tab,
        Key.Enter => Library.IO.Key.Enter,
        Key.Pause => Library.IO.Key.Pause,
        Key.CapsLock => Library.IO.Key.Capslock,
        Key.Escape => Library.IO.Key.Esc,
        Key.Space => Library.IO.Key.Space,
        Key.PageUp => Library.IO.Key.PageUp,
        Key.PageDown => Library.IO.Key.PageDown,
        Key.End => Library.IO.Key.End,
        Key.Home => Library.IO.Key.Home,
        Key.Left => Library.IO.Key.LeftArrow,
        Key.Up => Library.IO.Key.UpArrow,
        Key.Right => Library.IO.Key.RightArrow,
        Key.Down => Library.IO.Key.DownArrow,
        Key.PrintScreen => Library.IO.Key.PrintScreen,
        Key.Insert => Library.IO.Key.Insert,
        Key.Delete => Library.IO.Key.Delete,
        Key.Number0 => Library.IO.Key.D0,
        Key.Number1 => Library.IO.Key.D1,
        Key.Number2 => Library.IO.Key.D2,
        Key.Number3 => Library.IO.Key.D3,
        Key.Number4 => Library.IO.Key.D4,
        Key.Number5 => Library.IO.Key.D5,
        Key.Number6 => Library.IO.Key.D6,
        Key.Number7 => Library.IO.Key.D7,
        Key.Number8 => Library.IO.Key.D8,
        Key.Number9 => Library.IO.Key.D9,
        Key.A => Library.IO.Key.A,
        Key.B => Library.IO.Key.B,
        Key.C => Library.IO.Key.C,
        Key.D => Library.IO.Key.D,
        Key.E => Library.IO.Key.E,
        Key.F => Library.IO.Key.F,
        Key.G => Library.IO.Key.G,
        Key.H => Library.IO.Key.H,
        Key.I => Library.IO.Key.I,
        Key.J => Library.IO.Key.J,
        Key.K => Library.IO.Key.K,
        Key.L => Library.IO.Key.L,
        Key.M => Library.IO.Key.M,
        Key.N => Library.IO.Key.N,
        Key.O => Library.IO.Key.O,
        Key.P => Library.IO.Key.P,
        Key.Q => Library.IO.Key.Q,
        Key.R => Library.IO.Key.R,
        Key.S => Library.IO.Key.S,
        Key.T => Library.IO.Key.T,
        Key.U => Library.IO.Key.U,
        Key.V => Library.IO.Key.V,
        Key.W => Library.IO.Key.W,
        Key.X => Library.IO.Key.X,
        Key.Y => Library.IO.Key.Y,
        Key.Z => Library.IO.Key.Z,
        Key.Keypad0 => Library.IO.Key.Numpad0,
        Key.Keypad1 => Library.IO.Key.Numpad1,
        Key.Keypad2 => Library.IO.Key.Numpad2,
        Key.Keypad3 => Library.IO.Key.Numpad3,
        Key.Keypad4 => Library.IO.Key.Numpad4,
        Key.Keypad5 => Library.IO.Key.Numpad5,
        Key.Keypad6 => Library.IO.Key.Numpad6,
        Key.Keypad7 => Library.IO.Key.Numpad7,
        Key.Keypad8 => Library.IO.Key.Numpad8,
        Key.Keypad9 => Library.IO.Key.Numpad9,
        Key.KeypadMultiply => Library.IO.Key.Multiply,
        Key.KeypadAdd => Library.IO.Key.Add,
        Key.KeypadSubtract => Library.IO.Key.Subtract,
        Key.KeypadDecimal => Library.IO.Key.Decimal,
        Key.KeypadDivide => Library.IO.Key.Divide,
        Key.F1 => Library.IO.Key.F1,
        Key.F2 => Library.IO.Key.F2,
        Key.F3 => Library.IO.Key.F3,
        Key.F4 => Library.IO.Key.F4,
        Key.F5 => Library.IO.Key.F5,
        Key.F6 => Library.IO.Key.F6,
        Key.F7 => Library.IO.Key.F7,
        Key.F8 => Library.IO.Key.F8,
        Key.F9 => Library.IO.Key.F9,
        Key.F10 => Library.IO.Key.F10,
        Key.F11 => Library.IO.Key.F11,
        Key.F12 => Library.IO.Key.F12,
        Key.F13 => Library.IO.Key.F13,
        Key.F14 => Library.IO.Key.F14,
        Key.F15 => Library.IO.Key.F15,
        Key.F16 => Library.IO.Key.F16,
        Key.F17 => Library.IO.Key.F17,
        Key.F18 => Library.IO.Key.F18,
        Key.F19 => Library.IO.Key.F19,
        Key.F20 => Library.IO.Key.F20,
        Key.F21 => Library.IO.Key.F21,
        Key.F22 => Library.IO.Key.F22,
        Key.F23 => Library.IO.Key.F23,
        Key.F24 => Library.IO.Key.F24,
        Key.NumLock => Library.IO.Key.Numlock,
        Key.ScrollLock => Library.IO.Key.ScrollLock,
        Key.ShiftLeft => Library.IO.Key.Shift,
        Key.ShiftRight => Library.IO.Key.Shift,
        Key.ControlLeft => Library.IO.Key.Control,
        Key.ControlRight => Library.IO.Key.Control,
        Key.AltLeft => Library.IO.Key.Alt,
        Key.AltRight => Library.IO.Key.Alt,
        Key.Slash => Library.IO.Key.Slash,
        _ => Library.IO.Key.None,
    };
}