[[Items]]
ID         = "light"
Name       = "Light"
Icon       = "block/light.0.png"
MaxStack   = 100
[Items.Placeable]
Type       = "brick"
ID         = "light"
[Items.ViewModel]
Mesh       = "cube.obj"
Material   = "bricks/light"
Position.X = 0.4
Position.Y = -0.4
Position.Z = -0.5
Rotation.X = 0
Rotation.Y = 30
Rotation.Z = 0
Scale.X    = 0.25
Scale.Y    = 0.25
Scale.Z    = 0.25
[Items.WorldModel]
Mesh       = "cube.obj"
Material   = "bricks/light"