ID = "swordfish"
Name = "Swordfish"
Description = "The Swordfish engine."
Author = "Chase Huegel"
Website = "https://github.com/ChaseHuegel"
Source = "https://github.com/ChaseHuegel/swordfish-engine"

RootPathOverride = "assets"
AssembliesPath = ""
Assemblies = [
    "Swordfish.dll",
]