<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <Version>0.1.0-alpha</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.6" />
        <PackageReference Include="NATS.Net" Version="2.7.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WaywardBeyond.Shared.Config\WaywardBeyond.Shared.Config.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <!-- Generate code is being explicitly included, don't also implicitly include it -->
        <DefaultItemExcludes>$(DefaultItemExcludes);CodeGen/Output/**/*.cs</DefaultItemExcludes>
    </PropertyGroup>
    <Target Name="RunCodeGen" BeforeTargets="CoreCompile">
        <Exec Command="nsdc -r -p -i CodeGen -o ./CodeGen/Output"/>
        <ItemGroup>
            <Compile Include="CodeGen/Output/**/*.cs"/>
        </ItemGroup>
    </Target>

</Project>
