name: NuGet
on:
  push:
    branches:
      - main
jobs:
  nuget:
    name: Pack and Publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pack
        run: dotnet pack -c Release -o .
      - name: Push
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate