name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Download NSDC
      run: curl -L https://github.com/ChaseHuegel/needlefish/releases/download/v1.2.1/nsdc.v1.2.1.linux64.zip -o nsdc.zip
    - name: Setup NSDC
      run: unzip nsdc.zip
    - name: Setup Environment
      run: echo "$PWD" >> $GITHUB_PATH
    - name: Publish
      run: dotnet publish "WaywardBeyond.Client.Launcher/WaywardBeyond.Client.Launcher.csproj" -c Release -r win-x64 -o artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Wayward Beyond ${{ github.ref_name }}
        path: artifact
